[2025-09-10T12:52:23.234303] [INFO] [SYSTEM] Start new run (run_id=e6715c7b-4e17-4ed9-8e7c-ba90c847cd4a)
[2025-09-10T12:52:57.518998] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 0
[2025-09-10T12:52:57.519999] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Counts computed for kit build.
[2025-09-10T12:52:59.554768] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Base64 length bounds computed for pad selection.
[2025-09-10T12:53:05.051725] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using PAD size (bucketized): 128
[2025-09-10T12:53:08.886557] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T12:53:08.892498] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='kmYloNOnDALma7cbh4wcLw=='
[2025-09-10T12:53:09.017069] [INFO] [CRYPTO] debug_utils.py:log_crypto_event:267 - Crypto operation
[2025-09-10T12:53:09.018070] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2id parameters confirmed for kit.
[2025-09-10T12:53:09.018070] [WARNING] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness below policy threshold.
[2025-09-10T12:53:11.583065] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness evaluation complete.
[2025-09-10T12:53:11.584066] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:53:11.586065] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 1 failed
[2025-09-10T12:53:11.587065] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:53:11.588065] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 2 failed
[2025-09-10T12:53:11.588065] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:53:11.589065] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 3 failed
[2025-09-10T12:53:11.590064] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:53:11.590064] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 4 failed
