[2025-09-10T11:11:40.310288] [INFO] [SYSTEM] Start new run (run_id=9730dc5a-5d2f-407d-8411-4849898924db)
[2025-09-10T11:12:03.707718] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 0
[2025-09-10T11:12:03.707718] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Counts computed for kit build.
[2025-09-10T11:12:06.676991] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Base64 length bounds computed for pad selection.
[2025-09-10T11:12:08.876574] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using PAD size (bucketized): 128
[2025-09-10T11:12:11.649523] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T11:12:12.404032] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T11:12:13.174840] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T11:12:13.267076] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T11:12:13.267076] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='U4u48bvofNvkGFutb7P2Lw=='
[2025-09-10T11:12:13.359595] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - Argon2 param check failed for m=1
[2025-09-10T11:12:13.359595] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T11:12:13.360595] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='U4u48bvofNvkGFutb7P2Lw=='
[2025-09-10T11:12:13.592638] [INFO] [CRYPTO] debug_utils.py:log_crypto_event:267 - Crypto operation
[2025-09-10T11:12:13.593644] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2 params adjusted for compatibility.
[2025-09-10T11:12:13.593644] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2id parameters confirmed for kit.
[2025-09-10T11:12:13.594642] [WARNING] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness below policy threshold.
[2025-09-10T11:12:15.110590] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness evaluation complete.
[2025-09-10T11:12:15.112608] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T11:12:15.113607] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 1 failed
[2025-09-10T11:12:15.114610] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T11:12:15.115608] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 2 failed
