[2025-09-10T11:04:01.376170] [INFO] [SYSTEM] Start new run (run_id=6545aeef-98cb-4782-a155-0a9322d9bfa5)
[2025-09-10T11:04:50.477761] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 0
[2025-09-10T11:04:50.478811] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Counts computed for kit build.
[2025-09-10T11:04:53.416541] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Base64 length bounds computed for pad selection.
[2025-09-10T11:04:56.599659] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using PAD size (bucketized): 128
[2025-09-10T11:04:59.521742] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T11:05:00.030042] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T11:05:00.572370] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T11:05:00.668767] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T11:05:00.669767] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='va563shpETsp8Yxp8k8MPQ=='
[2025-09-10T11:05:00.760371] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - Argon2 param check failed for m=1
[2025-09-10T11:05:00.761369] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T11:05:00.761369] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='va563shpETsp8Yxp8k8MPQ=='
[2025-09-10T11:05:00.990882] [INFO] [CRYPTO] debug_utils.py:log_crypto_event:267 - Crypto operation
[2025-09-10T11:05:00.991882] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2 params adjusted for compatibility.
[2025-09-10T11:05:00.992883] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2id parameters confirmed for kit.
[2025-09-10T11:05:00.998671] [WARNING] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness below policy threshold.
[2025-09-10T11:05:03.214493] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness evaluation complete.
[2025-09-10T11:05:03.220677] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - Error splitting REAL secret
