[2025-09-10T12:51:11.191337] [INFO] [SYSTEM] Start new run (run_id=2ecbe3e5-049a-4694-868e-3e429ce8bfae)
[2025-09-10T12:51:39.250292] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 0
[2025-09-10T12:51:39.251294] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Counts computed for kit build.
[2025-09-10T12:51:41.121287] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Base64 length bounds computed for pad selection.
[2025-09-10T12:51:45.189332] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using PAD size (bucketized): 128
[2025-09-10T12:51:50.943934] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T12:51:50.950217] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='rlPPd/b68PS4qC5CLmfLKg=='
[2025-09-10T12:51:51.075815] [INFO] [CRYPTO] debug_utils.py:log_crypto_event:267 - Crypto operation
[2025-09-10T12:51:51.076815] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2id parameters confirmed for kit.
[2025-09-10T12:51:51.077815] [WARNING] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness below policy threshold.
[2025-09-10T12:51:55.268197] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness evaluation complete.
[2025-09-10T12:51:55.269196] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:51:55.271195] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 1 failed
[2025-09-10T12:51:55.271195] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:51:55.272194] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 2 failed
[2025-09-10T12:51:55.273195] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:51:55.274195] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 3 failed
[2025-09-10T12:51:55.274195] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:51:55.275195] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 4 failed
