[2025-09-10T12:43:00.310334] [INFO] [SYSTEM] Start new run (run_id=a3973240-c1e0-4778-84bd-b55dbe9f70d4)
[2025-09-10T12:43:25.117736] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 0
[2025-09-10T12:43:25.117736] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Counts computed for kit build.
[2025-09-10T12:43:27.249226] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Base64 length bounds computed for pad selection.
[2025-09-10T12:43:29.513793] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using PAD size (bucketized): 128
[2025-09-10T12:43:33.009758] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T12:43:33.634218] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T12:43:34.471400] [INFO] [GENERAL] debug_utils.py:log_debug:238 - User int input valid: 1
[2025-09-10T12:43:34.569178] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T12:43:34.570182] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='6Sg9JLB/kuMgjMEIHjJsXQ=='
[2025-09-10T12:43:34.660689] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - Argon2 param check failed for m=1
[2025-09-10T12:43:34.661689] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Using user-provided password='SECQ_param_check' (raw).
[2025-09-10T12:43:34.661689] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Starting Argon2id KDF (Noble). pass='SECQ_param_check', salt(b64)='6Sg9JLB/kuMgjMEIHjJsXQ=='
[2025-09-10T12:43:34.894659] [INFO] [CRYPTO] debug_utils.py:log_crypto_event:267 - Crypto operation
[2025-09-10T12:43:34.895660] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2 params adjusted for compatibility.
[2025-09-10T12:43:34.896650] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Argon2id parameters confirmed for kit.
[2025-09-10T12:43:34.896650] [WARNING] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness below policy threshold.
[2025-09-10T12:43:48.730189] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Combinatorial hardness evaluation complete.
[2025-09-10T12:43:48.731188] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:43:48.732188] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 1 failed
[2025-09-10T12:43:48.733188] [INFO] [CRYPTO] debug_utils.py:log_debug:238 - Attempting sss_split for REAL path.
[2025-09-10T12:43:48.733188] [ERROR] [GENERAL] debug_utils.py:log_exception:286 - REAL sss_split attempt 2 failed
